name: PR
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      # - name: Cypress install
      #   uses: cypress-io/github-action@v2
      #   with:
      #     runTests: false

      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn prettier:check

      # - name: 'Build for env: ${{ github.base_ref }}'
      #   if: ${{ github.base_ref == 'develop' || github.ref == 'refs/heads/develop' }}
      #   run: CI= yarn build:ci
      #   env:
      #     REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID: ${{ secrets.REACT_APP_AWS_COGNITO_IDENTITY_POOL_ID__DEV }}
      #     REACT_APP_AWS_COGNITO_REGION: ${{ secrets.REACT_APP_AWS_COGNITO_REGION__DEV }}
      #     REACT_APP_AWS_PROJECT_REGION: ${{ secrets.REACT_APP_AWS_PROJECT_REGION__DEV }}
      #     REACT_APP_AWS_USER_POOLS_ID: ${{ secrets.REACT_APP_AWS_USER_POOLS_ID__DEV }}
      #     REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID: ${{ secrets.REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID__DEV }}
      #     REACT_APP_AWS_PUBSUB_ENDPOINT: ${{ secrets.REACT_APP_AWS_PUBSUB_ENDPOINT__DEV }}
      #     REACT_APP_CREATE_ENVELOPE_API: ${{ secrets.REACT_APP_CREATE_ENVELOPE_API__DEV }}
      #     AWS_COGNITO_NEWFIRMADMIN_USERNAME: ${{ secrets.AWS_COGNITO_NEWFIRMADMIN_USERNAME__DEV }}
      #     AWS_COGNITO_NEWFIRMADMIN_PASSWORD: ${{ secrets.AWS_COGNITO_NEWFIRMADMIN_PASSWORD__DEV }}

      # - name: Save build folder
      #   if: ${{ github.base_ref == 'develop' || github.ref == 'refs/heads/develop' }}
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build
      #     if-no-files-found: error
      #     path: build

  # ui-chrome-tests:
  #   timeout-minutes: 20
  #   runs-on: ubuntu-latest
  #   container:
  #     image: cypress/browsers:node16.13.0-chrome95-ff94
  #     options: --user 1001
  #   needs: test
  #   if: ${{ github.base_ref == 'develop' || github.ref == 'refs/heads/develop' }}
  #   strategy:
  #     # when one test fails, DO NOT cancel the other
  #     # containers, because this will kill Cypress processes
  #     # leaving the Dashboard hanging ...
  #     # https://github.com/cypress-io/github-action/issues/48
  #     fail-fast: false
  #     matrix:
  #       # run copies of the current job in parallel
  #       containers: [1]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Write the cypress.env.json file
  #       run: |
  #         echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json

  #     - name: Download the build folders
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: build
  #         path: build

  #     - run: yarn global add serve

  #     - name: 'UI Tests - Chrome'
  #       uses: cypress-io/github-action@v2
  #       with:
  #         start: yarn serve
  #         wait-on: 'http://localhost:3000'
  #         wait-on-timeout: 180
  #         browser: chrome
  #         record: true
  #         parallel: true
  #         group: 'UI - Chrome'
  #         # spec: cypress/tests/ui/*
  #       env:
  #         CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
  #         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  #         # Recommended: pass the GitHub token lets this action correctly
  #         # determine the unique run id necessary to re-run the checks
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
